"use client";
import HeadingLinkable from "@/components/HeadingLinkable";
import Highlighter from "@/components/Highlighter";
import InlineReference from "@/components/InlineReference";
import Math from "@/components/Math";
import Paragraph from "@/components/Paragraph";
import { ReferenceItem } from "@/components/Reference";
import SectionTitle from "@/components/SectionTitle";
import { List, ListItem, OrderedList, Text } from "@chakra-ui/react";
import { tree } from "next/dist/build/templates/app-page";
import { references } from "./fokker-planck-references";

export default function FokkerPlanck({
  readingList,
  readingListHandler,
}: {
  readingList: ReferenceItem[];
  readingListHandler: any;
}) {
  return (
    <>
      <SectionTitle title="Semigroups" />
      <Paragraph>
        Let <Math latex="X" /> be a Banch space. Suppose for every{" "}
        <Math latex="t\geq 0" /> we associate a bounded linear mapping (also
        called an operator) <Math display={true} latex="Q_t: X\rightarrow X" />
        so as to have
        <OrderedList pl="2em" pb="1em" pt="1em" styleType="lower-roman">
          <ListItem>
            <Math latex="Q_0=I" /> is the identity
          </ListItem>
          <ListItem>
            <Math latex="Q_{t+s}=Q_t\circ Q_s" />
            for all <Math latex="s,\,t\geq 0" />
          </ListItem>
          <ListItem>
            <Math latex="\lim_{t\downarrow 0} ||Q_t(x)-x||=0" /> for every{" "}
            <Math latex="x\in X" />
          </ListItem>
        </OrderedList>
        If (i) and (ii) hold, the family of operators{" "}
        <Math latex="\{Q_t\}_{t\geq 0}" /> is called a{" "}
        <Highlighter isRound={false}>semigroup</Highlighter> of a single
        parameter. In view of (ii) we shall later see that under favourable
        circumstances it is possible to represent the operators in exponential
        form <Math display={true} latex="Q_t=\exp(At)" />
        for an operator <Math latex="A" />. To begin this investigation, for
        every
        <Math latex="\varepsilon >0" /> we associate to{" "}
        <Math latex="Q_\varepsilon" />
        the operator
        <Math
          display={true}
          latex="A_\varepsilon x=\frac{1}{\varepsilon}\left[Q_\varepsilon (x) - x\right]"
        />
        for every <Math latex="x\in X" />. Define the operator{" "}
        <Math
          display={true}
          latex="Ax=\lim_{\varepsilon\downarrow 0} A_\varepsilon x"
        />
        whenever the limit exists (in topology generated by the norm of the
        Banach space <Math latex="X" padding={false} />
        ), in which case we say <Math latex="x\in \mathscr{D}_A" /> is in the
        domain of <Math latex="A" />. Observe that{" "}
        <Math latex="\mathscr{D}_A" /> is a vector subspace of{" "}
        <Math latex="X" /> and <Math latex="A" /> is a linear operator. The
        operator <Math latex="A" /> is called the{" "}
        <Highlighter isRound={false}>infinitesimal generator</Highlighter>
        of the semigroup <Math latex="\{Q_t\}" />.
      </Paragraph>
      <SectionTitle title="Exponential Representation of Semigroups" />
      <Paragraph>
        We can say several things about the semigroup <Math latex="\{Q_t\}" />{" "}
        satisfying (1)-(3) above:
        <OrderedList pl="2em" pb="1em" pt="1em">
          <ListItem>
            There are constants <Math latex="C,\,\gamma" /> such that
            <Math latex="||Q_t||\leq Ce^{\gamma t}" display={true} />
            for every <Math latex="t\geq 0" padding={false} />.
          </ListItem>
          <ListItem>
            <Math latex="t\mapsto Q_t(x)" /> is a continuous map of{" "}
            <Math latex="[0,\infty)" /> into
            <Math latex="X" /> for every <Math latex="x\in X" padding={false} />
            .
          </ListItem>
          <ListItem>
            <Math latex="\mathscr{D}_A" /> is dense in <Math latex="X" /> and{" "}
            <Math latex="A" /> is closed.
          </ListItem>
          <ListItem>
            The differential equation{" "}
            <Math latex="\frac{d}{dt}Q_t(x)=(A\circ Q_t)(x)=(Q_t\circ A)(x)" />
            holds for every <Math latex="x\in \mathscr{D}_A" padding={false} />.
          </ListItem>
          <ListItem>
            For every <Math latex="x\in X" padding={true} />{" "}
            <Math
              latex="Q_t(x)=\lim_{\varepsilon\downarrow 0}e^{t A_\varepsilon}(x)"
              display={true}
            />
            the convergence is uniform on every compact subset of{" "}
            <Math latex="[0,\infty)" padding={false} />.
          </ListItem>
          <ListItem>
            If <Math latex="\lambda \in \mathbb{C}" /> with real part{" "}
            <Math latex="\text{Re}\, \lambda > \gamma" />, then the integral
            <Math
              display={true}
              latex="R_\lambda (x) = \int_0^\infty e^{-\lambda t}Q_t(x)\, dt"
            />
            defines a bounded linear operator{" "}
            <Math latex="R_\lambda: X\rightarrow X" /> called the{" "}
            <Highlighter isRound={false}>resolvant</Highlighter> of the
            semigroup <Math latex="\{Q_t\}" /> whose range is{" "}
            <Math latex="x\in \mathscr{D}_A" />, and which is the inverse of{" "}
            <Math latex="\lambda I - A" padding={false} />.
          </ListItem>
        </OrderedList>
        Proof of (1)-(6) above can be found in Rudin
        <InlineReference
          reference={references[0]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <Paragraph>
        Property (5) above is almost{" "}
        <Math display={false} latex="Q_t=\exp(At)" /> which we set out to seek,
        but under what conditions? The following theorem answers this: any of
        these three statements imply the other two
        <OrderedList pl="2em" pb="1em" pt="1em">
          <ListItem>
            <Math latex="Q_t=e^{tA}" /> for all{" "}
            <Math latex="t\geq 0" padding={true} /> where{" "}
            <Math latex="A: X\rightarrow X" /> is a bounded linear operator.
          </ListItem>
          <ListItem>
            <Math latex="\lim_{\varepsilon \downarrow 0}||Q_\varepsilon - I||=0" />
          </ListItem>
          <ListItem>
            <Math latex="\mathscr{D}_A=X" />
          </ListItem>
        </OrderedList>
        A proof of this theorem can be found in Rudin
        <InlineReference
          reference={references[0]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <Paragraph>
        The representation of semigroups specialized to Hilbert space is also
        interesting to describe: if the semigroup consists of normal operators
        satisfying the condition condition (iii), then for a normal
        infinitesimal generator <Math latex="A" /> we have{" "}
        <Math latex="Q_t=e^{tA}" padding={false} />. Similarly, if the semigroup
        satisfying (iii) consists of unitary operators, then we have
        representation <Math latex="Q_t=e^{itS}" display={true} /> for some
        self-adjoint operator <Math latex="S" padding={false} />.
      </Paragraph>
      <SectionTitle title="Hille-Yosida Theorem" />
      <Paragraph>
        Which operators generate semigroups? Conversely, what properties do
        infinitesimal generators of semigroups have? The answers lies in the{" "}
        <Highlighter>Hille-Yosida theorem</Highlighter>, which states:
      </Paragraph>
      <Paragraph>
        A densely defined operator <Math latex="A" /> in a Banach space{" "}
        <Math latex="X" /> is the infinitesimal generator of a semigroup{" "}
        <Math latex="\{Q_t\}_{t\geq 0}" /> satisfying properties (i)-(iii) above{" "}
        <Text as="b">if and only if</Text>
        there are constances <Math latex="C,\, \gamma" /> such that
        <Math
          display={true}
          latex="||(\lambda I - A)^{-m}||\leq C(\lambda-\gamma)^{-m}"
        />
        for all <Math latex="\lambda > \gamma" /> and all positive integers{" "}
        <Math latex="m" padding={false} />.
      </Paragraph>
      <Paragraph>
        A proof of this theorem can be found in Rudin
        <InlineReference
          reference={references[0]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <SectionTitle title="Feller Semigroup" />
      <Paragraph>
        The starting point for the study of Feller processes is to regard the{" "}
        <Text as="b">transition function (t.f.)</Text> of Markov processes as
        operators on a function space. Concretely, let <Math latex="P_{s,t}" />{" "}
        be a (possibly time dependent) t.f. and let <Math latex="f" />
        be a function from a suitable function space, then the integral
        <Math display={true} latex="Tf(x) = \int P_{s,t}(x, dy) f(y)" />
        defines an operator. In general, the{" "}
        <Highlighter>Chapman-Kolmogorov relations</Highlighter> are{" "}
        <Math
          latex="\int P_{s,t}(x,dy)P_{t,v}(y, A)=P_{s,v}(x, A)"
          display={true}
        />{" "}
        for any <Math latex="0\leq s< t < v" padding={false} />. When the t.f.
        <Math latex="P_{s,t}" /> depends on <Math latex="s,\,t" /> through the
        difference <Math latex="s-t" /> alone, then we write{" "}
        <Math latex="P_t" /> for
        <Math latex="P_{0,t}" /> and call it a{" "}
        <Text as="b">homogenenous transition function</Text>. In this situation
        the Chapman-Kolmogorov relations turns into a form
        <Math
          latex=" P_{t+s}(x,A)=\int P_{s}(x,dy)P_{t}(y, A)"
          display={true}
        />
        that reminds us of the semigroup relation (ii){" "}
        <Math latex="T_{t+s}=T_t\circ T_s" display={true} />.
      </Paragraph>
      <Paragraph>
        To make precise the semigroup appearence, let <Math latex="E" /> be a
        locally compact space with countable base (abbrev. LCCB space), and let{" "}
        <Math latex="C_0=C_0(E)" /> be the set of real valued continuous
        functions <Math latex="E" /> that vanishes at infinity. Recall that a{" "}
        <Text as="b">positive operator</Text> maps positive functions to
        positive functions. A <Highlighter>Feller semigroup</Highlighter> on{" "}
        <Math latex="C_0(E)" />
        is a family <Math latex="\{T_t\}_{t\geq 0}" /> of positive linear
        operators on <Math latex="C_0(E)" /> such that
        <OrderedList pl="2em" pb="1em" pt="1em">
          <ListItem>
            <Math latex="T_0=I" /> and <Math latex="||T_t||\leq 1" /> for every{" "}
            <Math latex="t" padding={false} />.
          </ListItem>
          <ListItem>
            <Math latex="T_{t+s}=T_t\circ T_s" /> for any pair{" "}
            <Math latex="s,t" padding={false} />.
          </ListItem>
          <ListItem>
            <Math latex="\lim_{\downarrow 0} ||T_tf - f|| = 0" /> for every{" "}
            <Math latex="f\in C_0(E)." padding={false} />
          </ListItem>
        </OrderedList>
        Each Feller semigroup on <Math latex="E" /> gives rises to a unique
        homogenenous transition function <Math latex="\{P_t\}_{t\geq 0}" /> such
        that
        <Math latex="T_tf(x)=\int P_t(x,dy)f(y)" display={true} /> for every{" "}
        <Math latex="f\in C_0" /> and every{" "}
        <Math latex="x\in E" display={false} />. We call the transition
        associated to the Feller semigroup a{" "}
        <Highlighter>Feller transition function</Highlighter>. The necessary and
        sufficient condition for a t.f. to be a Feller t.f. is as follows (proof
        in
        <InlineReference
          reference={references[2]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
        )
        <OrderedList pl="2em" pb="1em" pt="1em">
          <ListItem>
            <Math latex="P_t C_0\subset C_0" />
          </ListItem>
          <ListItem>
            <Math latex="\lim_{t\downarrow 0} P_t f(x)=f(x)" /> for all{" "}
            <Math latex="f\in C_0" /> and{" "}
            <Math latex="x\in E" padding={false} />.
          </ListItem>
        </OrderedList>
        The notation <Math latex="P_tf=\int P_t(x,dy)f(y)" /> and{" "}
        <Math
          latex="P_t C_0 = \left\{\,P_tf: \, f\in C_0\, \right\}"
          display={!true}
          padding={!true}
        />
      </Paragraph>
      <Paragraph>
        A <Highlighter isRound={!true}>Feller process</Highlighter> is a Markov
        process having a Feller transition function.
      </Paragraph>
      <SectionTitle title="Convolution Semigroup" />
      <Paragraph>
        An example of Feller semigroups is furnished by{" "}
        <Text as="b">convolution semigroups</Text>, constructed out from
        families
        <Math latex="\{\mu_t\}_{t\geq 0}" /> of probability measures on{" "}
        <Math latex="\mathbb{R}^d" /> satisfying
        <OrderedList pl="2em" pb="1em" pt="1em">
          <ListItem>
            <Math latex="\mu_t \star \mu_s = \mu_{t+s}" />
          </ListItem>
          <ListItem>
            <Math latex="\lim_{t\downarrow 0}\mu_t = \mu_0" /> in the vague
            topology.
          </ListItem>
        </OrderedList>
        From this Feller semigroup we can derive a Feller transition function
        <Math
          latex="P_t(x, A)=\int_{\mathbb{R}^d} 1_A(x+y)\mu_t(dy)"
          display={true}
        />
        The transition functions of{" "}
        <Highlighter>d-dimensional Brownian motion</Highlighter>
        are of this type. For 1-dimensional Brownian motion, the t.f. come from
        convolotion of probability measures <Math latex="P_t(x, \cdot)" /> given
        by the densities
        <Math
          display={true}
          latex="g_t(y-x)=\frac{1}{\sqrt{2\pi t}}e^{-(y-x)^2 / 2t}"
        />
        If the transition function of a process <Math latex="X" /> is given by a
        convolution semigroup <Math latex="\{\mu_t\}" />, then{" "}
        <Math latex="X" />
        has stationary independent increments. The law of the increment of{" "}
        <Math latex="X_t-X_s" /> is <Math latex="\mu_{t-s}" padding={false} />.
        A proof can be found in
        <InlineReference
          reference={references[2]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
        Stationary above means the law of the increment <Math latex="X_t-X_s" />{" "}
        depends on <Math latex="s" /> and <Math latex="t" /> only through their
        difference <Math latex="t-s" padding={false} />.
      </Paragraph>
      <Paragraph>
        Conversely if a Feller process has stationary increments, then its
        transition functions are generated from convolution semigroup with{" "}
        <Math latex="\lim_{t\downarrow 0}\mu_t = \mu_0" padding={false} />. Such
        a process is called a <Highlighter>Lévy process</Highlighter>.
      </Paragraph>
      <SectionTitle title="Forward Backward Eqautions" />
      <Paragraph>
        The abstract results about semigroups and their infinitesimal generators
        can be applied to the case of Feller processes. In particular we focus
        on the property that <Math latex="t\mapsto P_t f" /> is differentiable
        and
        <Math latex="\frac{d}{dt} P_tf = P_tAf= AP_t f " display={true} />
        where as above <Math latex="A" /> denotes the infinitesimal generator of
        the (Feller) semigroup.
      </Paragraph>
      <Paragraph>
        We can view <Math latex="P_tAf=\langle P_t, Af\rangle" /> as a pairing
        of the measure <Math latex="P_t(x,\cdot)" /> and the function{" "}
        <Math latex="Af(x)" padding={false} />. With this duality in mind we
        write
        <Math
          latex="\langle P_t, Af\rangle=\langle A^* P_t, f\rangle"
          display={true}
        />
        With <Math latex="A^*" /> being the formal adjoint of <Math latex="A" />{" "}
        we can rewrite
        <Math latex="\frac{d}{dt} P_tf = P_tAf" display={false} /> as
        <Math
          latex="\frac{d}{dt} P_t(x,\cdot) = A^*P_t(x,\cdot)"
          display={true}
        />
        this is called the <Text as="b">forward equation</Text> or the{" "}
        <Highlighter>Fokker-Planck equation</Highlighter>. The left side appears
        to involve differentiating a measure, however, given that measures can
        be expressed in terms of functions (ex. a probability measure is
        represented by its density function, and moreover absolutely continuous{" "}
        measure by the so called Radon-Nikodym derivative), the above
        differential equation makes sense. Analogously, this equation is called
        the <Text as="b">backwards equation</Text>
        <Math
          latex="\frac{d}{dt} P_t(x,\cdot) = AP_t (x,\cdot) "
          display={true}
        />
      </Paragraph>
      <SectionTitle title="Generator for Brownian Motion" />
      <Paragraph>
        Denote by <Math latex="C^2_0=C^2_0(\mathbb{R}^d)" /> the space of twice
        continuously differentiable functions where the function and its first
        two derivatives vanish at inifity. Then for Brownian motion in{" "}
        <Math latex="\mathbb{R}^d" /> started at the origin, the infinitesimal
        generator is <Math latex="A=\frac{1}{2}\Delta" padding={false} />. In
        other words{" "}
        <Math
          latex="Af=\frac{1}{2}\sum_{i=1}^d \frac{\partial^2f}{\partial x_i^2}"
          display={true}
        />
        It can be shown that for <Math latex="d=1" /> the domain of the operator{" "}
        <Math latex="\mathscr{D}_A=C_0^2" /> and for
        <Math latex="d>1" /> <Math latex="\mathscr{D}_A" /> is the proper
        subspace of <Math latex="C_0" /> functions <Math latex="f" /> such that{" "}
        <Math latex="\Delta f\in C_0" padding={!true} /> in the sense of
        distributions (since such functions need not possess second
        derivatives).
      </Paragraph>
      <Paragraph>
        For Brownian motions, the forward-backward equations are
        <Math
          latex="\frac{d}{dt} P_tf = \frac{1}{2}P_t\Delta f= \frac{1}{2}\Delta P_t f "
          display={true}
        />
        this is why the normal density functions <Math latex="g_t" /> defined
        above and its higher dimensional analogues are{" "}
        <Text as="b">fundamental solutions</Text> of the{" "}
        <Highlighter>heat equaiton</Highlighter>{" "}
        <Math
          latex="\frac{\partial f}{\partial t}+\frac{1}{2}\Delta f=0"
          display={true}
        />
      </Paragraph>
      <Paragraph>
        If <Math latex="B" /> is a <Math latex="d-" padding={false} />
        dimensional Brownian motion started at the origin, then for a{" "}
        <Math latex="d\times d" /> matrix <Math latex="\sigma" /> we can define
        a Markov process starting off origin{" "}
        <Math latex="X_t=x+\sigma B_t" padding={false} />. The corresponding
        infinitesimal generator is
        <Math
          latex="Af=\frac{1}{2}\sum_{i,j}\gamma_{ij}\partial_{ij} f"
          display={true}
        />
        where <Math latex="\gamma=\sigma\sigma^t" padding={false} />.
      </Paragraph>
      <Paragraph>
        Proofs can be found in
        <InlineReference
          reference={references[2]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <SectionTitle title="Generators of Feller Processes" />
      <Paragraph>
        To describe the infinitesimal generator for Feller processes more
        generally, suppose <Math latex="\{P_t\}" padding={true} /> is a Feller
        semigroup on <Math latex="\mathbb{R}^d" padding={true} /> and{" "}
        <Math latex="C_K^\infty\subset\mathscr{D}_A" padding={false} />. Then
        for every realtively compact open set <Math latex="U" />, there exists
        functions <Math latex="a_{ij},\, b_i,\, c" /> on <Math latex="U" /> and
        a kernel
        <Math latex="N" /> such that for <Math latex="f\in C^2_K" /> and{" "}
        <Math latex="x\in U" />
        <Math
          latex="Af(x)=c(x)f(x)+\sum_i b_i(x)\partial_i f(x) +\sum_{i,j}a_{ij}(x)\partial_{ij} f(x)+"
          display={true}
        />
        <Math
          latex="\int_{\mathbb{R}^d \backslash\{x\}}\left[f(y)-f(x)-1_{U(y)}\sum_i(y_i-x_1)\partial_i f(x)\right]N(x,dy)"
          display={true}
        />
        where <Math latex="N(x,\,\cdot\,)" /> is a Radon measure on{" "}
        <Math latex="\mathbb{R}^d \backslash\{x\}" />, the matrix{" "}
        <Math latex="a(x)=[a_{ij}(x)]" /> is symmetric positive semidefinite,
        <Math latex="c \leq 0" /> and <Math latex="a,\, c" /> do not depend on{" "}
        <Math latex="U" padding={false} />.
      </Paragraph>
      <Paragraph>
        The idea behind this generator <Math latex="A" /> is that the
        infinitesimal purturbation consists of adding a translation{" "}
        <Math latex="b(x)" padding={false} />, a Gaussian process with
        covariance <Math latex="a(x)" padding={false} />, jumps given by{" "}
        <Math latex="N(x,\,\cdot\,)" padding={false} />, and{" "}
        <Math latex="c(x)f(x)" padding={false} /> accounts for scenarios for the
        process of being killed.
      </Paragraph>
      <Paragraph>
        If the process has continuous paths, then its infinitesimal generator is
        given on
        <Math latex="C^2_K" /> by the{" "}
        <Highlighter>
          semi-elliptic second order differential operator
        </Highlighter>
        <Math
          display={true}
          latex="Af(x)=c(x)f(x)+\sum_i b_i(x)\partial_i f(x) +\sum_{i,j}a_{ij}(x)\partial_{ij} f(x)"
        />
        where <Math latex="a(x)" /> is symmetric positive semidefinite.
      </Paragraph>
      <Paragraph>
        More details about this section can be found in
        <InlineReference
          reference={references[1]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>{" "}
        and{" "}
        <InlineReference
          reference={references[2]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <SectionTitle title="Diffusion Process" />
      <Paragraph>
        Next we will define diffusion processes in the context of the above
        discussions. Suppose for <Math latex="x" /> the matrices{" "}
        <Math latex="a(x)" /> is symmetric positive semidefinite. Let{" "}
        <Math latex="b(x)" /> be a vector field, and suppose further the maps{" "}
        <Math latex="x\mapsto a(x)" /> and <Math latex="x\mapsto b(x)" />
        are Boreal measurable and locally bounded. We associate to the pair{" "}
        <Math latex="(a,b)" /> the second order differential operator
        <Math
          display={true}
          latex="L=\frac{1}{2}\sum_{i,j=1}^d a_{ij}(\,\cdot\,)\partial_{ij} + \sum_{i=1}^d b_i(\,\cdot\,)\partial_i "
        />
        A Markov process <Math latex="X" /> with state space{" "}
        <Math latex="\mathbb{R}^d" /> is said to be a{" "}
        <Highlighter>diffusion process</Highlighter>
        with generator <Math latex="L" /> if <Math latex="X" /> has continuous
        paths, and if for any <Math latex="x\in\mathbb{R}^d" /> and any{" "}
        <Math latex="f\in C_K^\infty" />
        <Math
          latex="\mathbb{E}_x[f(X_t)]=f(x)+\mathbb{E}_x\left[\int_0^t Lf(X_s)\,ds\right]"
          display={true}
        />
        we say that <Math latex="X" /> has covariance or{" "}
        <Highlighter>diffusion coefficient</Highlighter> <Math latex="a" />
        and drift <Math latex="b" padding={false} />. If further introduce
        dependence on time
        <Math latex="s" /> then correspondingly
        <Math
          display={true}
          latex="L_s=\frac{1}{2}\sum_{i,j=1}^d a_{ij}(s,\,\cdot\,)\partial_{ij} + \sum_{i=1}^d b_i(s,\,\cdot\,)\partial_i "
        />
        we obtain <Highlighter>non-homogeneous diffusion</Highlighter> if for
        any <Math latex="f\in C_K^\infty" /> and <Math latex="s<t" />
        <Math
          latex="\mathbb{E}_{s,x}[f(X_t)]=f(x)+\mathbb{E}_{s,x}\left[\int_s^t L_uf(X_u)\,du\right]"
          display={true}
        />
      </Paragraph>
      <SectionTitle title="Diffusion Approximation of Markov Chains" />
      <Paragraph>
        We now sketch out in non-rigourous terms the approximation of{" "}
        <Text as="b">discrete-time Markov chains</Text> by diffuion and more
        generally continuous time Markov processes. We begin a discussion of
        convergence of Feller processes{" "}
        <Math latex="X^n\rightarrow X" padding={false} />. As a Feller process
        can be specified by various equivalent objects: the Feller semigroup,
        the infinitesimal generator, we can describe this convergence in a
        multitude of equivalent ways. We do not make precise the various modes
        of convergences here and refer to the interested reader to{" "}
        <InlineReference
          reference={references[2]}
          readingList={readingList}
          readingListHandler={readingListHandler}
        ></InlineReference>
      </Paragraph>
      <Paragraph>
        Let <Math latex="\{X^n\}_{n\in \mathbb{N}}" padding={!false} /> and{" "}
        <Math latex="X" /> be Feller processes in a state space
        <Math latex="S" /> with semigroups <Math latex="\{T_{n,t}\}" /> and{" "}
        <Math latex="\{T_t\}" /> respectively, and generators
        <Math latex="A_n" /> and <Math latex="A" /> on the domains{" "}
        <Math latex="\mathscr{D}_n" /> and <Math latex="\mathscr{D}" />{" "}
        respectively. Let <Math latex="D" /> be a so called{" "}
        <Text as="b">core</Text> of <Math latex="\mathscr{D}" /> which is a
        special vector subspace of <Math latex="\mathscr{D}" padding={false} />.
        Then the following (non-precise) statements are equivalent
        <OrderedList pl="2em" pb="1em" pt="1em" styleType="lower-roman">
          <ListItem>
            Any element <Math latex="f" /> in the core can be approximated by a
            sequence <Math latex="f_n\in\mathscr{D}_n" /> in the sense that{" "}
            <Math latex="f_n\rightarrow f" /> and{" "}
            <Math latex="A_nf_n\rightarrow Af" />{" "}
          </ListItem>
          <ListItem>
            Convergence of the operators <Math latex="T_{n,t}\rightarrow T_t" />{" "}
            for each
            <Math latex="t" />
          </ListItem>
          <ListItem>
            Convergence of functions <Math latex="T_{n,t}f\rightarrow T_tf" />{" "}
            for every <Math latex="f\in C_0" />
          </ListItem>
          <ListItem>
            The convergence in distribution of{" "}
            <Math latex="X_0^n\rightarrow X_0" /> implies convergence of Feller
            processes
            <Math latex="X^n\rightarrow X" />
          </ListItem>
        </OrderedList>
        This abstract convergence result can be applied to approximating Markov
        chains:
      </Paragraph>
      <Paragraph>
        Let <Math latex="\{Y^n\}_{n\in\mathbb{N}}" /> be discrete Markov chains
        in state space
        <Math latex="S" /> with transition operators{" "}
        <Math latex="\{U_n\}_{n\in\mathbb{N}}" />
        and let <Math latex="X" /> be a Feller process with semigroup{" "}
        <Math latex="\{T_t\}" /> and generator{" "}
        <Math latex="A" padding={false} />. Fix a core <Math latex="D" /> of the
        generator and let <Math latex="h_n > 0" /> be a sequence of numbers that
        converge to zero. Then the above equivalent statements apply to the
        processes and operators
        <Math display={true} latex="X^n_t=Y^n_{[t/h_n]}" />
        <Math display={true} latex="T_{n,t}=U_n^{[t/h_n]}" />
        <Math display={true} latex="A_n=h_n^{-1}(U_n-I)" />
        In particular we can approximate the discrete-time Markov chain by
        diffusion processes.
      </Paragraph>
    </>
  );
}
